#!/bin/sh
set -e

if [ -x "/etc/init.d/aurora-scheduler" ]; then
if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
invoke-rc.d aurora-scheduler stop || true
else
/etc/init.d/aurora-scheduler stop || true
fi
fi
